version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      alloy:
        patterns: ["alloy*"]
      tokio:
        patterns: ["tokio*"]
      tower:
        patterns: ["tower*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
